# Example Configuration File for DCAM
general:
  year: 2022
  month: 12
  day: 22
  verbose: 1
  outputDir: # If user wants to output result files to an external drive, otherwise save to current output directory
aircraft:
  time: 30 # [s]
  frequency: 400 # [Hz]
  waypoints: SCurveFlightPath
  lookaheadDistance: 50 # [m]
  initialState:
    latitude: 32.612788581736706 # [degrees]
    longitude: -85.43535088858731 # [degrees]
    u: 75 # [m/s]
    v: 0 # [m/s]
    w: 0 # [m/s]
    p: 0 # [rad/s]
    q: 0 # [rad/s]
    r: 0 # [rad/s]
    x: 0 # [m]
    y: 0 # [m]
    z: -1000 # [m]
    phi: 0 # [rad]
    theta: 4*pi/180 # [rad]
    psi: pi # [rad]
